# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ad-detector-simulator-example', ['ad-detector-simulator'])
    obj.source = 'ad-detector-simulator-example.cc'

    obj = bld.create_ns3_program('read-coordinatesToNs2MobilityHelper', ['ad-detector-simulator', 'mobility'])
    obj.source = 'read-coordinatesToNs2MobilityHelper.cc'

    obj = bld.create_ns3_program('convert_rawdata_to_ns3mobilityhelper', ['ad-detector-simulator'])
    obj.source = 'convert_rawdata_to_ns3mobilityhelper.cc'

    obj = bld.create_ns3_program('read-coordinatesToVector2D', ['ad-detector-simulator'])
    obj.source = 'read-coordinatesToVector2D.cc'
